# Generated by Django 2.1.7 on 2020-05-02 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmodel',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 2, 14, 10, 327631, tzinfo=utc)),
        ),
    ]
