# Generated by Django 2.1.7 on 2020-05-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONIC', 'Electronic'), ('FURNITURE', 'Furniture'), ('JOBS', 'Jobs'), ('WEBSITE', 'Website'), ('MOBILE APP', 'Mobile App'), ('GENERAL', 'General')], default='ELECTRONIC', max_length=20),
        ),
    ]
