# Generated by Django 2.1.7 on 2020-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='console.ConsolePicture/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='console.ConsolePicture/bytes/filename/mimetype'),
        ),
    ]
